### ISSUE TITLE
Can you make a version with NetStandard instead of NetCore ? 

### ISSUE THREAD

**Issue by ststeiger** [yzrmn/System.CoreFX.Forms#3]
Can you make a version with NetStandard instead of NetCore ?

**Comment by yzrmn** [comment]
I remember that it wasn't compatible with .NET Standard 2.0, so we would have to wait for the next version :)

However, in which scenario do you need .NET Standard support?

**Comment by ststeiger** [comment]
Never mind, I've already done so. I can make a pull request, if you like ;)

**Comment by yzrmn** [comment]
Sorry for late reply, had some stuff to do...

> Not compatible ? You mean it didn't compile, or it didn't run ?

I'm not quite sure anymore what went wrong exactly, I think it had something to do with conflicting namespaces. Or maybe I tried something which is now disabled anyway.
In the end I figured why to support .NET Standard after all? You are only able to use it on PCs and .NET Core covers that fully. Also I wanted the framework to act as a drop-in replacement for old Windows Forms application and leave the namespaces as is. Is this even possible with from .NET Framework?

So if you see a big benefit in using .NET Standard I would suggest that you just fork the whole project :)
I don't put any more time into this project anymore because I'm currently working on a C# graphics framework which will hopefully someday has a decent System.Drawing wrapper to make all the UI stuff happen.

**Comment by ststeiger** [comment]
Oh well, the reason for .NET-Standard is that it's easier to port code to NetStandard, plus you can also use it if you build something with the full .NET framewok, then. 
The reason the switch didn't work for you was probably that you didn't nuget System.Reflection.Emit. 

System.Drawing.Common is already on nuget, anyway - only missing very few in terms of API compatibility now. 

But thanks for the project anyway, it was a life-safer, and I am perfectly fine with keeping my own fork ;)

**Comment by yzrmn** [comment]
> Don't know why you make a System.Drawing-wrapper, System.Drawing.Common is already on nuget - only missing very few in terms of API compatibility now.

System.Drawing.Common has some drawbacks that I wish to eliminate with my implementation. In short the new framework will be faster (already is), SVG compliant and fully portable.

> But thanks for the project anyway, it was a life-safer, and I am perfectly fine with keeping my own fork ;)

You're welcome! :)

**Comment by jnm2** [comment]
@ststeiger Targeting .NET Standard is how you say "this library can run on any .NET-Standard-supporting platform." That's not true for this library; this library can't ruin on any platform except .NET Core.

> Oh well, the reason for .NET-Standard is that it's easier to port code to NetStandard than to .NET Core (in general)

In my experience the opposite is true. .NET Standard has fewer APIs than either .NET Framework or .NET Core.

> plus you can also use it if you build something with the full .NET framewok, then.

That's a good reason to make the package target `netcoreapp2.0;net472` and contain empty `net472` lib folders. You don't need to retarget `netcoreapp2.0` as `netstandard2.0` in order to achieve this.

**Comment by ststeiger** [comment]
@jnm2: I haven't looked at the details, but theoretically, you could use this library with the full .net framework - as long as you don't reference System.Windows.Forms. 

That is because mono reimplements the entire .NET Framework - also to work under Windows. 
Now it might not make much sense, since the mono-implementation is less feature-complete and less tested, but you can. 

Also, since the .NET Framework assemblies are strongly referenced, this should still work if some dependency of the .NET Framwork references System.Windows.Forms. 

But yes, leaving System.Windows.Forms empty on net472 would make more sense.

**Comment by jnm2** [comment]
@ststeiger 

> e.g. my netstandard-project where I use this - reportviewer for .net and .net-core - reportviewer code has some remaining references to winforms.

So what happens when I use your .NET Standard report viewer on UWP or Xamarin.iOS? Shouldn't that itself be targeted as `netcoreapp2.0;net47` or something similar?

**Comment by ststeiger** [comment]
That's actually a good question. 
The better question would be what does WinForms code do in a project used in WebForms ? 
My guess is that the cause is a common component used in both WinForms-ReportViewer and WebForms ReportViewer, with the parts of the code using WinForms actually only being called in a WinForms viewer. 

If that's the case, then the WinForms code is only needed for compilation, and it should work on UWP or Xamarin, too. 

If the WinForms elements are used for data-filtering or something like that, then it probably depends if the elements used (and the elements loaded when those classes are initialized) are only managed code (classes, interfaces, EventArgs). 
If that (full managed code) is the case, then it probably works too. 

If there are pinvokes, then: 
for xamarin.ios, depends if ios exports the same dylibs, with the same binary signature, which is unlikely. 
So that will probably crash either your Xamarin app, or iOS. 

for UWP, i don't know - can it even pinvoke there ?  
If the same dlls with the same binary signatures are exposed, then it might even "work" - but that is unlikely. 
If it works, it probably expects a mouse, not a touchscreen. 
So that will probably either crash your UWP app, or your phone. 
But it would be fun having a WinForm inside a UWP app ;)
