### ISSUE TITLE
Could you please provide a Nuget Package for System.CoreFX.Forms?

### ISSUE THREAD

**Issue by bbenetskyy** [yzrmn/System.CoreFX.Forms#6]
It will be really nice to have a NuGet package with a name like `System.CoreFX.Forms`  available in NuGet package list.

If you don't want to provide NuGet package what is your way to connect `System.CoreFX.Forms` to the projects?

**Comment by yzrmn** [comment]
Hi, I'm not really comfortable with pushing the library to NuGet because it has many issues.
However, you could just build it and reference it the old way...

```
  <ItemGroup>
    <Reference Include="System.CoreFX.Forms">
      <HintPath>Assemblies\System.CoreFX.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/11163354/47270119-39086780-d567-11e8-89a6-aff91786fce4.png)

Another way would be to copy the whole source into your project root.

**Comment by bbenetskyy** [comment]
@yzrmn  Even if it has issues you could publish it in alfa or beta version and after each bug fixing or adding new control/feature, you will just publish newer NuGet package with next minor or major version changes according to changes from the previous release.

For someone who wants to use your project is more easy to install a NuGet package instead of compiling a project add existed `.dll` or add your project to the solution and add dependency to it.

Also if there some bugs that should be resolved ASAP, users of your `Framework` in any time could download sources and make PR with fixes.

What do you think about it? Or you still prefer standard project linking

**Comment by yzrmn** [comment]
That's the thing, I mostly abandoned this project because it does what I needed it to do - to bridge the time for WinForms until [.NET Core 3](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/) happens. However, I thought somebody else could profit from my work or is even willing to improve it in ways that I cannot (e.g. full Unix support). In the meantime I put all my efforts into developing a native C# high performance 2D framework.
Also someone installing this from NuGet might have different expectations that this project might not fulfill. I personally think that it does not meet the quality requirements to publish it, sorry.
If you really like to see it on NuGet, I won't stop you though ;)

**Comment by bbenetskyy** [comment]
Thanks for quick response and details ;)

**Comment by kejsardamberg** [comment]
I find this code so magically useful while porting my own projects to multitargeting Net Core and NetFramework. However it's so frustratingly painful to include DLLs in nuget packages for Visual Studio 2017 type projects - especially when having a long dependency chain between nuget packages in multiple layers. Would it be ok with you if I publish this brilliant software as System.CoreFX.Forms.Unofficial on nuget.org? That would indeed make my life so much easier.

**Comment by yzrmn** [comment]
Hi :) Well, I think you could try to copy the whole folder into your project and it just might work. However, if you feel that publishing on NuGet is the best solution to your problem then I certainly won't stop you ;) But you could use a little more unobtrusive name to not confuse people that are expecting a high quality framework.
